<?php 
/* Turkish */

$crl[0]='85';
$crl[1]='<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-9">';
$crl[2]='SimpleChat! 1.3';
$crl[3]='Sound: On/Off';
$crl[4]='Onay';
$crl[5]='Ýptal';
$crl[6]='Þifre';
$crl[7]='Renkleri Deðiþtir...';
$crl[8]='KIZGIN';
$crl[9]='COOL';
$crl[10]='ÜZGÜN';
$crl[11]='AVAZ AVAZA';
$crl[12]='TEBESSÜM';
$crl[13]='ZITT';
$crl[14]='KALIN';
$crl[15]='ITALÝK';
$crl[16]='RENK';
$crl[17]='Tarih / Zaman';
$crl[18]='Ad';
$crl[19]='Mesaj';
$crl[20]='Geçmiþ (150 satýr)';
$crl[21]='Frame destekleyen tarayýcý gerektirir.';
$crl[22]='Users Online';
$crl[23]='No Users Online...';
$crl[24]='Ad';
$crl[25]='Chat';
$crl[26]='Chat [Yenile]';
$crl[27]='Geçmiþ';
$crl[28]='Geçmiþe dön [Yenile]';
$crl[29]='Sistemden Çýk';
$crl[30]='sistemden Çýk [Ad deðiþtir]';
$crl[31]='Temizle';
$crl[32]='Geçmiþi temizle [þifre korumalý]';
$crl[33]='Hakkýnda';
$crl[34]='Yenile: ';
?>