<?php
/* Czech - pavel-at-kotrla-dot-com */

$crl[0]='48';
$crl[1]='<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-2">';
$crl[2]='SimpleChat! 1.3';
$crl[3]='Sound: On/Off';
$crl[4]='Poslat';
$crl[5]='Zru¹it';
$crl[6]='Heslo';
$crl[7]='Zmìnit barvy...';
$crl[8]='ROZHNÌVANÝ';
$crl[9]='V POHODÌ';
$crl[10]='SMUTNÝ';
$crl[11]='JÁSAJÍCÍ';
$crl[12]='USMÌVAVÝ';
$crl[13]='MHOUØÍCÍ';
$crl[14]='TEXT TUÈNÌ';
$crl[15]='TEXT KURZÍVOU';
$crl[16]='TEXT BAREVNÌ';
$crl[17]='Datum / Èas';
$crl[18]='Pøezdívka';
$crl[19]='Zpráva';
$crl[20]='HISTORIE (150 øádkù)';
$crl[21]='Tato stránka potøebuje prohlí¾eè s podporou rámcù.';
$crl[22]='Pøihlá¹ení u¾ivatelé';
$crl[23]='®ádní pøihlá¹ení u¾ivatelé...';
$crl[24]='Pøihlásit jako';
$crl[25]='Chat';
$crl[26]='Vstoupit do chatu [Aktualizovat]';
$crl[27]='Historie';
$crl[28]='Prohlédnout si historii [Aktualizovat]';
$crl[29]='Odhlásit';
$crl[30]='Odhlásit [Zmìnit pøezdívku]';
$crl[31]='Vymazat';
$crl[32]='Vymazat chat a historii [chránìno heslem]';
$crl[33]='O chatu';
$crl[34]='Aktualizovat: ';
?>