<?php
/* Slovak ---  Ondrej Sykora --- E-MAIL : faidron@host.sk */

$crl[0]='48';
$crl[1]='<meta http-equiv="Content-Type" content="text/html; charset=windows-1250">';
$crl[2]='SimpleChat! 1.3';
$crl[3]='Sound: On/Off';
$crl[4]='Posla';
$crl[5]='Zrui';
$crl[6]='Heslo';
$crl[7]='Zmeni farby...';
$crl[8]='ROZHNEVANÝ';
$crl[9]='V POHODE';
$crl[10]='SMUTNÝ';
$crl[11]='NADENÝ';
$crl[12]='USMIEVAVÝ';
$crl[13]='ZACHMÚRENÝ';
$crl[14]='TEXT TUÈNE';
$crl[15]='TEXT KURZÍVOU';
$crl[16]='TEXT FAREBNE';
$crl[17]='Dátum / Èas';
$crl[18]='Prezívka';
$crl[19]='Zpráva';
$crl[20]='HISTÓRIA ( 150 riadkov )';
$crl[21]='Táto stránka potrebuje prehliadaè s podporou rámcov.';
$crl[22]='Users Online';
$crl[23]='No Users Online...';
$crl[24]='Prihlási sa ako';
$crl[25]='Chat';
$crl[26]='Vstúpi do chatu [ aktualizova ]';
$crl[27]='História';
$crl[28]='Prezrie si históriu [ aktualizova ]';
$crl[29]='Odhlási';
$crl[30]='Odhlási [ zmeni prezívku ]';
$crl[31]='Vymaza';
$crl[32]='Vymaza chat a históriu [ chránené heslom ]';
$crl[33]='O chatu';
$crl[34]='Aktualizova: ';
?>